name: map_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  equatable: ^2.0.5
  injectable: ^2.1.0
  google_sign_in: ^5.4.4
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  firebase_database: ^10.0.9
  permission_handler: ^10.2.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
